FROM registry.redhat.io/rhel9/rhel-bootc:9.7

RUN dnf install -y \
    @workstation-product-environment \
    podman \
    cockpit \
    cockpit-podman \
    firewalld \
    sudo \
    python3 \
    python3-pip \
    mosquitto-clients \
    v4l-utils \
    mesa-libGL \
    libglvnd-glx \
    iputils \
    iproute \
    bind-utils \
    net-tools \
    nmap-ncat \
    tcpdump \
    git \
    vim \
    jq \
    htop \
    tmux \
    firefox \
    && dnf clean all

# DO NOT DO THIS IN PRODUCTION ENVIRONMENTS (for demo troubleshooting only)
RUN echo "root:redhat123" | chpasswd

# Create demo user
RUN useradd -m demouser

# Add demouser to wheel group
RUN usermod -aG wheel demouser

# Passwordless sudo
RUN echo "demouser ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/demouser && \
    chmod 0440 /etc/sudoers.d/demouser

# Enable required services
RUN systemctl enable cockpit.socket
RUN systemctl enable NetworkManager

# Boot to graphical desktop
RUN systemctl set-default graphical.target

# Enable automatic login
RUN mkdir -p /etc/gdm && \
    printf '[daemon]\nAutomaticLoginEnable=True\nAutomaticLogin=demouser\n' > /etc/gdm/custom.conf

# Prevent screen sleep / lock and disable Activities overview
RUN mkdir -p /etc/dconf/db/local.d /etc/dconf/db/local.d/locks && \
    printf '[org/gnome/desktop/session]\nidle-delay=uint32 0\n\n[org/gnome/desktop/screensaver]\nlock-enabled=false\n\n[org/gnome/shell]\nstartup-mode=\"user\"\n' > /etc/dconf/db/local.d/00-demo-settings && \
    printf '/org/gnome/desktop/session/idle-delay\n/org/gnome/desktop/screensaver/lock-enabled\n' > /etc/dconf/db/local.d/locks/00-demo-settings && \
    dconf update

# Create systemd user service to launch demo browser
RUN mkdir -p /home/demouser/.config/systemd/user

RUN printf '[Unit]\nDescription=Launch Demo Browser\nAfter=graphical-session.target\n\n[Service]\nType=oneshot\nExecStart=/usr/bin/firefox --kiosk http://127.0.0.1:6080\n\n[Install]\nWantedBy=default.target\n' \
> /home/demouser/.config/systemd/user/demo-browser.service

# Timer to delay browser launch (so browser doesn't show app not available if inference container hasn't come online yet)
RUN printf '[Unit]\nDescription=Delay Demo Browser Launch\n\n[Timer]\nOnBootSec=10\nUnit=demo-browser.service\n\n[Install]\nWantedBy=timers.target\n' \
> /home/demouser/.config/systemd/user/demo-browser.timer

# Fix ownership
RUN chown -R demouser:demouser /home/demouser/.config

# Enable the timer
RUN su - demouser -c "systemctl --user enable demo-browser.timer"

# Prevent OS auto-updates during the conference
RUN systemctl mask bootc-fetch-apply-updates.timer

# Prevent container auto-updates
RUN systemctl mask podman-auto-update.timer
RUN systemctl mask podman-auto-update.service
